replicaCount: 2
image:
  repository: gcr.io/heptio-images/ks-guestbook-demo
  tag: 0.2
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
  path: /
  hosts:
    - chart-example.local
